### PR TITLE
fix(typescript): update rich-text types

### LINKED ISSUE #1534: Missing type for wysiwyg content
Type RichTextContent aka wysiwyg entry content is represented like this: 
image

I am trying to write a conditional for assets: 
image

It looks like 'embedded-asset-block' needs to be added to RichTextNodeType in index.d.ts like this (I added it for the pic):
image

This is what needs to be updated: https://github.com/contentful/contentful.js/blob/d25879c40058b237b268e42de9ba9354f6616b70/index.d.ts#L263

### PR DESCRIPTION
**Pull request by z0al**
Fixes #1534 
Related #1569

### CODE REVIEW

File: index.d.ts [hunk 1]
```diff
@@ -260,27 +272,25 @@ interface RichTextData {
     target?: RichTextDataTarget;
 }
 
-type RichTextNodeType = 'text' | 'heading-1' | 'heading-2' | 'heading-3' | 'heading-4' | 'heading-5'
-    | 'heading-6' | 'paragraph' | 'hyperlink' | 'entry-hyperlink' | 'asset-hyperlink'
-    | 'unordered-list' | 'ordered-list' | 'list-item' | 'blockquote' | 'hr' | 'embedded-entry-block'
-    | 'embedded-entry-inline';
+// Requires TypeScript v4.1+
+type RichTextNodeType = `${BLOCKS}` | `${INLINES}` | 'text';
```
Comment (z0al) [inline index.d.ts:276]: This is the main change. The rest is prettier

**Review by marcolink — APPROVED** [review]
🚢
